fix: ajustando codigo do sonar

diff --git a/.github/workflows/feature.yaml b/.github/workflows/feature.yaml
--- a/.github/workflows/feature.yaml
+++ b/.github/workflows/feature.yaml
@@ -12,48 +12,62 @@ permissions:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
+    # Checkout code from the repository
     - name: Check out the repository
       uses: actions/checkout@v2
       with:
-        ref: ${{ github.ref }}
+        ref: ${{ github.ref }} # Checkout the current branch
 
+    # Set up .NET SDK
     - name: Set up .NET
       uses: actions/setup-dotnet@v2
       with:
-        dotnet-version: '8.0.x'
+        dotnet-version: '8.0.x' # Using the latest .NET 8.0 version
 
+    # Install dotnet-coverage tool
+    - name: Install dotnet-coverage tool
+      run: dotnet tool install --global dotnet-coverage
+
+    # Install dependencies
     - name: Install dependencies
       run: dotnet restore src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln
 
+    # Build the project
     - name: Build the project
       run: dotnet build --no-restore --configuration Release src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln
 
-    - name: Run tests and collect coverage
-      run: |
-        dotnet test src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln \
-          --no-build \
-          --configuration Release \
-          --verbosity normal \
-          --collect:"XPlat Code Coverage" \
-          --results-directory ./TestResults \
-          --logger:"trx" \
-          /p:CollectCoverage=true \
-          /p:CoverletOutputFormat=openxml \
-          /p:CoverletOutput=./TestResults/coverage.opencover.xml
+    # Run tests and collect code coverage in XML format
+    - name: Run tests and collect code coverage
+      # run: dotnet-coverage collect "dotnet test src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln" -f xml -o "TestResults/coverage.xml"
+      run: dotnet test src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln --configuration Release --collect:"XPlat Code Coverage"
 
-    - name: SonarCloud Scan
-      uses: SonarSource/sonarcloud-github-action@v2
-      env:
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    # Check if coverage file exists
+    # - name: Check if coverage file exists
+    #   run: |
+    #     if [ ! -f "TestResults/coverage.xml" ]; then
+    #       echo "Coverage file not found!"
+    #       exit 1
+    #     fi
+
+    - uses: chill-viking/dotnet-sonar-scanner@v2
+      name: Scan and Publish
       with:
-        args: >
-          -Dsonar.projectKey=PosTechFiap33_controle-pedidos-api-pedidos \ -Dsonar.organization=postechfiap33 \ -Dsonar.host.url=https://sonarcloud.io \ -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
-
-    - name: Generate coverage report
-      run: |
-        # Gerar o relatório de cobertura com base no arquivo de cobertura coletado
-        dotnet reportgenerator -reports:./TestResults/coverage.opencover.xml -targetdir:./TestResults/coverage-report -reporttypes:Html
+        sonar-project-key: 'PosTechFiap33_controle-pedidos-api-pedidos'
+        sonar-org-key: 'postechfiap33'
+        token: ${{ secrets.GITHUB_TOKEN }}
+        sonar-token: ${{ secrets.SONAR_TOKEN }}
+        working-directory: './src/app/ControlePedido.Pedidos'
+        checkout: false
+    # SonarCloud Scan
+    # - name: SonarCloud Scan
+    #   uses: SonarSource/sonarcloud-github-action@v2
+    #   with:
+    #     organization: postechfiap33
+    #     token: ${{ secrets.SONAR_TOKEN }}
+    #     projectKey: PosTechFiap33_controle-pedidos-api-pedidos
+    #     projectName: controle-pedidos-api-pedidos
+    #     extraProperties: |
+    #       sonar.coverageReportPaths=**/TestResults/*/coverage.cobertura.xml
